### ISSUE TITLE
Bugzilla log attachment is empty

### ISSUE THREAD

**Issue by mruprich** [fedora-infra/the-new-hotness#136]
Attachment in bugzilla which contains log from rebase-helper is always empty. 
See an example here: https://bugzilla.redhat.com/show_bug.cgi?id=1395933

**Comment by jeremycline** [comment]
Thanks for the report @mruprich!

It looks like this is happening because the log is being marked as a patch when it is, in fact, not a patch. If you navigate to the [attachment directly](https://bugzilla.redhat.com/attachment.cgi?id=1221428) without the ``action=diff`` parameter in the URL in the comment, you can actually see the log. Luckily, a PR was merged today (https://github.com/fedora-infra/the-new-hotness/pull/129) that stops setting the ``patch=True`` flag for logs from rebase-helper, so the next release should fix this! I don't have a solid idea when the next release will be, but in the next couple weeks I hope.

**Comment by jeremycline** [comment]
I'm going to close this since the production hotness no longer attaches logs
