### ISSUE TITLE
new-hotness didn't file a bug about ipdb-0.10.2

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/the-new-hotness#155]
I have [python-ipdb](https://admin.fedoraproject.org/pkgdb/package/rpms/python-ipdb/) configured for bugs to be filed upon new upstream releases, but I don't believe a bug was ever filed for ipdb-0.10.2. Anitya did find the update.

**Comment by jeremycline** [comment]
I poked around in the logs and this happened because the old the-new-hotness used repoquery and it failed to find the package in rawhide so it dropped the message. The new version uses mdapi and it's much more reliable. The exact same problem was seen in https://github.com/release-monitoring/anitya/issues/432 and the staging the-new-hotness behaved correctly. I'm going to deploy the new the-new-hotness to production today.

I'm going to optimistically close this as fixed, but let me know if this happens again once the new version is up and running.

**Comment by bowlofeggs** [comment]
On Tue, 2017-02-14 at 03:07 -0800, Jeremy Cline wrote:
> I'm going to optimistically close this as fixed, but let me know if
> this happens again once the new version is up and running.

Sounds good!

Given your explanation, this might have happened because the package
was orphaned and when I "adopted" it I immediately turned release
monitoring on.
