### ISSUE TITLE
Allow bumping versions on copr as well

### ISSUE THREAD

**Issue by ibotty** [fedora-infra/the-new-hotness#168]
It might very well be out of scope, but very useful ;)

**Comment by jeremycline** [comment]
Hi @ibotty,

I can definitely see that being a helpful service, but I think it should be something new rather than part of the-new-hotness. I'd like the-new-hotness to have a single job: filing bugs or, in the future, PRs against the dist-git pagure. It would be fairly easy to implement a second fedmsg consumer that creates COPR builds when the-new-hotness or release-monitoring.org emits a message.

Thanks for the suggestion, though!

**Comment by ibotty** [comment]
Makes perfect sense.
