### ISSUE TITLE
Bugzilla 1429066 - owncloud-client

### ISSUE THREAD

**Issue by porjo** [fedora-infra/the-new-hotness#169]
As per instructions posted on [Bugzilla 1429066](https://bugzilla.redhat.com/show_bug.cgi?id=1429066)...

```
 Upstream Release Monitoring 2017-03-03 19:17:01 EST

An unexpected error occured creating the scratch build: please report 
this issue to the-new-hotness issue tracker at 
https://github.com/fedora-infra/the-new-hotness/issues
```

**Comment by jeremycline** [comment]
Hey @porjo,

It looks like owncloud started prefixing their releases with "v" and so release-monitoring.org started announcing version v2.3.0 instead of 2.30. When hotness dropped this into the specfile it created a URL that doesn't exist (https://download.owncloud.com/desktop/stable/owncloudclient-v2.3.0.tar.xz).

I've improved the error reporting of the-new-hotness in 0.8.1 and I'll put in production after the alpha freeze, and I've been working on making Anitya handle leading "v"s in versions (among other things), but in the mean time I've fixed https://release-monitoring.org/project/1987/ so it should announce the proper version.

**Comment by porjo** [comment]
> It looks like owncloud started prefixing their releases with "v" 

I don't understand - the [owncloud client git repo](https://github.com/owncloud/client/releases) shows release tags prefixed with 'v' going back several years!? What changed?

**Comment by jeremycline** [comment]
I think the really old versions in release-monitoring.org came from a time before the project was set to get its version updates from GitHub (which is why you see some versions without the leading 'v'). It looks like the-new-hotness scratch builds have been failing for owncloud-client for a long time, so I don't think anything except the error message changed. It should work next time, though.
