### ISSUE TITLE
Notifications from the-new-hotness still reference pkgdb

### ISSUE THREAD

**Issue by hobbes1069** [fedora-infra/the-new-hotness#227]
Messages about new versions where no monitoring is required state preferences can be changed in pkgdb which of course is gone.

It should probably reference:
https://pagure.io/releng/fedora-scm-requests/blob/master/f/README.md
or
https://fedoraproject.org/wiki/Infrastructure/WhatHappenedToPkgdb#How_do_I_change_the_upstream-monitoring.2Fanitya_flag_for_my_packages.3F

**Comment by Zlopez** [comment]
Yes, you are right, this should refer to fedora-scm-requests repository.

**Comment by Zlopez** [comment]
Just to be clear about this issue, by the notifications you mean fedmsg messages or [Fedora notifications](https://apps.fedoraproject.org/notifications)?

**Comment by hobbes1069** [comment]
Umm... The emails I get saying the-new-hotness saw a new version of a project but the maintainers were not interested in a BZ bug being filed?

**Comment by Zlopez** [comment]
If it's e-mail than it is probably related to Fedora notifications. I will look at it.

**Comment by Zlopez** [comment]
## Implementation details
This issue is in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/hotness.py when the pkgdb is the reason, why the update was dropped.

The fedmsg_meta function should be implemented in Fedora messaging schema anyway, so this should be solved in #222

**Comment by Zlopez** [comment]
This should be no longer true with new FMN released recently.
