### ISSUE TITLE
Despite receiving a notification about a new version, no bug was reported

### ISSUE THREAD

**Issue by contyk** [fedora-infra/the-new-hotness#23]
Today the new hotness notified me about a new version of perl-Test-Trap being available. However, even though the package is set to be monitored in pkgdb, no bug was ever filed.

Date: Tue, 24 Feb 2015 01:25:18 +0000 (UTC)
Subject: A new version of "Test-Trap" has been detected: "v0.3.2" in advance of "v0.3.0"

A new version of "Test-Trap" has been detected:  "v0.3.2" in advance of "v0.3.0"
        https://release-monitoring.org/project/3421/

Note unlike most CPAN projects, Test-Trap uses 'v' in the version string. Could it be the reason? Sounds unlikely but you never know :)

**Comment by ralphbean** [comment]
We had a temporary bug in the configuration for repoquery (the part where it figures out if 0.3.2 is greater or less than the version in the Fedora rawhide repos) that caused a number of packages to fail last night.  A fix was put in place shortly after.

I'm going to go ahead and close this since I'm almost certain it is fixed.  If you witness it again, please re-open.  Thank you :)
