### ISSUE TITLE
rpmautospec breaks Fedora patch creation / scratch builds

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#368]
When release-monitoring.org / anitya sees a new version for a Fedora package that uses rpmautospec (%autorelease, %autochangelog) and has "Monitoring + Scratch builds" turned on, the patch creation and scratch build are broken:

```
Skipping the scratch build because an SRPM could not be built: ['git', 'commit', '-a', '-m', 'Update to 2.6.0 (#2026174)'] returned 1: b'On branch rawhide\nYour branch is up to date with \'origin/rawhide\'.\n\nUntracked files:\n  (use "git add <file>..." to include in what will be committed)\n\tSRPMS/\n\nnothing added to commit but untracked files present (use "git add" to track)\n'
```

This looks like the new version is not correctly set in the .spec file (otherwise there would be actual changes?)

Example bug: https://bugzilla.redhat.com/show_bug.cgi?id=2026174

**Comment by gotmax23** [comment]
Any progress on this? This issue is affecting many of `go-sig`'s packages, as we've moved them to rpmautospec.

**Comment by Zlopez** [comment]
I thought this was already solved with release 1.0.0

**Comment by decathorpe** [comment]
Apparently not. This is a the-new-hotness crash output from yesterday:
https://bugzilla.redhat.com/show_bug.cgi?id=2035116#c1

PS: You might want to also adjust the commit message to the format bodhi understands, i.e. "Fixes / Closes RHBZ#1234567", like the one I used here: https://src.fedoraproject.org/rpms/rust-libc/c/0107538eaac96adf8523445451790c5dbaed557b?branch=rawhide

**Comment by Zlopez** [comment]
I can change the format of commit message, but can't do much about the patch itself. Hotness is using rpmdev-bumpspec from [rpmdevtools](https://pagure.io/rpmdevtools) for this, so the issue would be best reported there.

It looks like the [issue](https://pagure.io/rpmdevtools/issue/64) is already opened.

**Comment by decathorpe** [comment]
rpmdev-bumpspec does not modify .spec files that use rpmautospec. The issue you linked is already fixed, so it should be closed.

It looks like the problem is that the .spec file is not modified at all (i.e. the "Version" tag is not changed to the new version for the patch). Is it possible that the code used for setting "Version" fails for .spec files that use rpmautospec? For example, it should only set "Version" but leave "Release" alone, and not attempt to set it to "0%{?dist}" before calling rpmdev-bumpspec.

**Comment by gotmax23** [comment]
> rpmdev-bumpspec does not modify .spec files that use rpmautospec. The issue you linked is already fixed, so it should be closed.
> 
> It looks like the problem is that the .spec file is not modified at all (i.e. the "Version" tag is not changed to the new version for the patch). Is it possible that the code used for setting "Version" fails for .spec files that use rpmautospec? For example, it should only set "Version" but leave "Release" alone, and not attempt to set it to "0%{?dist}" before calling rpmdev-bumpspec.

It looks like the-new-hotness uses the `--new` option of `rpmdev-bumpspec` itself to update the `Version:` field. The problem is that, when `rpmdev-bumpspec` detects rpmautospec, it doesn't even update the `Version:` field; it does nothing at all. `rpmdev-bumpspec` needs to be updated to support the `--new` option without touching the release and changelog or the-new-hotness needs to implement an alternative solution.

**Comment by decathorpe** [comment]
Oh, so that is really a different issue in rpmdev-bumpspec. I didn't even know about the "--new" flag.

I reported this here: https://pagure.io/rpmdevtools/issue/91

**Comment by Zlopez** [comment]
What I can do in hotness is to skip the patch file creation if there is no change at all and just notify the user.

**Comment by Zlopez** [comment]
Thanks for info, when the version will be released I will update the package in production.

**Comment by Zlopez** [comment]
9.6 version which contains the fix was released [few days ago](https://src.fedoraproject.org/rpms/rpmdevtools), we just need to wait till it will be available in F34, which is currently used by hotness in production.

**Comment by gotmax23** [comment]
The update is now present in the repos.

**Comment by Zlopez** [comment]
I plan to release new version of hotness soon to address the API changes in Bugzilla.

**Comment by Zlopez** [comment]
Because the release of new version of Hotness is taking too long I updated the production note to latest version of rpmdevtools package in F34 manually.

The issue should be now gone. If you see it again please reopen the ticket.
