### ISSUE TITLE
File upload failed during scratch build

### ISSUE THREAD

**Issue by zmiklank** [fedora-infra/the-new-hotness#451]
I got [this](https://bugzilla.redhat.com/show_bug.cgi?id=2081878) error when the-new-hotness tried to scratch-build package postgresql-jdbc, saying, that upload of the srpm was unsuccessful. I noticed that the scratch build is done against rawhide, but the srpm, whose upload fails has the fc34 tag.

I think that this could be some bug in the-new-hotness, as my local scratch build has passed successfully. However, I am not really sure how to process further in debugging, as I have no access (that I know of) to the build logs.

**Comment by Zlopez** [comment]
SRPM file is obtained from this command `rpmbuild -D _sourcedir . -D _topdir . -bs <specfile>`. The reason why there is `fc34` tag is that the-new-hotness is running on F34 pod in production, but this newer was an issue.
The failed upload seems like an issue on koji side, probably there was some outage at the same time.

I'm closing this issue because this is not issue with the-new-hotness.

**Comment by zmiklank** [comment]
Thanks for the clarification!
