### ISSUE TITLE
hotness tried to map rubygem-ejs to an upstream project, but failed due to ambiguity.

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#46]
I received following FMN notification when requested rubygem-ejs in pkgdb:

```
hotness tried to map rubygem-ejs to an upstream project, but failed due to ambiguity.  6436 other projects share the same homepage
```

I am not really sure what does it complain about ...

**Comment by pypingou** [comment]
It was trying to map the package to the project in anitya, but failed to find a single project with this homepage (instead it found 6436 projects). Might be a bug, or maybe the URL in the spec is too broad.

**Comment by voxik** [comment]
It has standard rubygems URL, so my guess is that it is bug, that is why I reported the issue :)

**Comment by voxik** [comment]
Actually, listing all projects [1], it currently says "6552 projects found" which is quite close to the number reported by the-new-hotness

[1] https://release-monitoring.org/projects/

**Comment by voxik** [comment]
Also, there is already "ejs" project [1], which is different ejs to my rubygem-ejs. It is probably Node implementation of the same thing.

[1] https://release-monitoring.org/project/2218/

**Comment by voxik** [comment]
Created the project manually for now ....

**Comment by voxik** [comment]
I hit this issue again:

~~~
hotness tried to map rubygem-closure-compiler to an upstream project, but failed due to ambiguity.  7287 other projects share the same homepage
	https://bugzilla.redhat.com/show_bug.cgi?id=725733
~~~

**Comment by ralphbean** [comment]
For reference, here it is in datagrepper:  https://apps.fedoraproject.org/datagrepper/raw?category=hotness&package=rubygem-closure-compiler

**Comment by ralphbean** [comment]
OK, see this expanded query that includes both hotness and pkgdb messages:  https://apps.fedoraproject.org/datagrepper/raw?category=hotness&package=rubygem-closure-compiler&category=pkgdb

Hotness tries to do this mapping after a pkgdb.package.new message hits the bus.  Here's the message for that rubygem package:  https://apps.fedoraproject.org/datagrepper/id?id=2015-c503f756-1a6a-4340-a26c-f17fd66d1c50&is_raw=true&size=extra-large

Notice that the ``'upstream_url'`` field is empty!  It uses the homepage only to try and search anitya for a pre-existing entry, and, since it is blank, it fails.  Specifically, it hits this url:  http://release-monitoring.org/api/projects/?homepage= which returns *all* projects (as far as I can tell just by looking at the returned JSON).

So, we have two bugs here as I see it:

- When you query that anitya URL with an empty homepage, it should return only projects with an empty homepage, or return an error or something.
- pkgdb shouldn't allow new packages with an empty upstream_url, right?  Can we solve this there?

Without an upstream_url, hotness can't do anything reasonable with respect to anitya.

**Comment by voxik** [comment]
> pkgdb shouldn't allow new packages with an empty upstream_url, right? Can we solve this there?

I don't agree with this resolution. pkgdb should get the URL as soon as available from .spec file/SRPM and then setup the project in Anytia. pkgdb should require as less information as possible and this is definitely not essential, moreover it changes during the time, so I don't see any reason to bother to fill it up.

**Comment by voxik** [comment]
Actually, not sure how often is the URL / description / summary refreshed in pkgdb, but that should be the right moment to check the Anytia. 

Also, pkgdb could listen to Koji for first build to get the information ASAP.

**Comment by pypingou** [comment]
> Actually, not sure how often is the URL / description / summary refreshed in pkgdb, but that should be the right moment to check the Anytia. 

On a weekly basis via yum's metadata from rawhide > Fn+1 > Fn > Fn-1 > epel7 > el6 > el5...

**Comment by pypingou** [comment]
> so I don't see any reason to bother to fill it up.

Well now you do ;-)

**Comment by ralphbean** [comment]
> On a weekly basis

When this gets updated weekly, we could add a new codepath to the-new-hotness that listens for that and tries to map things in anitya again when the URL becomes available.  What fedmsg message does this publish?  Can you link to it in datagrepper?

**Comment by pypingou** [comment]
It should send a: http://fedora-fedmsg.readthedocs.org/en/latest/topics.html#pkgdb-package-update

**Comment by pypingou** [comment]
example: https://apps.fedoraproject.org/datagrepper/id?id=2015-ef49f802-2e10-4e33-b119-7dac241700b8&is_raw=true&size=extra-large

**Comment by voxik** [comment]
>> so I don't see any reason to bother to fill it up.
>
> Well now you do ;-)

I do but I disagree. Copy pasting stuff around all the time is not fun and there is definitely better solution. But may be it is just my bad sense of humor, in that case I apologize :)
