### ISSUE TITLE
A new version has been detected, same as the old version

### ISSUE THREAD

**Issue by jamesjer** [fedora-infra/the-new-hotness#503]
For at least a month now, I've been getting occasional emails with subjects like this:

A new version of "circle" has been detected: "1.6.5" newer than "1.6.5", packaged as "gap-pkg-circle"

That one is from today.  Package gap-pkg-circle has been on version 1.6.5 since April.  There are no newer tags upstream (https://github.com/gap-packages/circle/tags).

In every case, the Fedora package in question has been on the most recent version for months or, in one case, years.

**Comment by jamesjer** [comment]
Another instance today:
```
A new version of "icu4j" has been detected: "71-1" newer than "71-1", packaged as "icu4j"
```
In this case, upstream added a git tag yesterday.  It just wasn't a tag for an icu4j release.  Could the addition of non-release tags be triggering this behavior?

**Comment by Zlopez** [comment]
The check by release-monitoring.org is done periodically and if there is a new tag found and it's not in the filtered versions it will sent a message. The-new-hotness is then consuming the message and trying to recognize, if the newest version on the project is newer than the one in Fedora, and this is probably something when it gets confused. I would need to look at it more closely to be able to see what exactly happened in the-new-hotness.

**Comment by Zlopez** [comment]
Could you point me to a bugzilla ticket?

**Comment by jamesjer** [comment]
As far as I can tell, no bug was filed in any of these cases.

**Comment by Zlopez** [comment]
Is this a mail from notifications@fedoraproject.org? Because if yes, than the-new-hotness doesn't have anything to do with it. It just files new bugs in Bugzilla, whenever there is a new version.

**Comment by jamesjer** [comment]
Yes, it is.  I clearly don't know what the various pieces are or how they fit together.  Where should I file a bug, then?

**Comment by Zlopez** [comment]
This will be probably for [Anitya](https://github.com/fedora-infra/anitya), which is the app running on release-monitoring.org. Previously it emitted new message only when the new version was found. I changed this behavior to sent message each time a new version is found upstream not only if it's newer.

So the e-mail is actually correct, but wrongly worded. The service that is actually sending those e-mails ([FMN](https://github.com/fedora-infra/fmn)) is now being rewritten, because it's tied to the old messaging system fedora infra doesn't use anymore. I would say that this needs to be solved on FMN and if those two versions are the same just don't send anything. But I would wait till the service will be rewritten and then start looking at this. In the meantime you can open the ticket there and link it here.

**Comment by jamesjer** [comment]
I opened https://github.com/fedora-infra/anitya/issues/1438.  Thank you for the help.  I will wait patiently for the service to be rewritten.
