### ISSUE TITLE
Scratch build notified on wrong review request

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/the-new-hotness#83]
The review request for `nodejs-each` (https://bugzilla.redhat.com/show_bug.cgi?id=1279127) just got notified of a scratch build for `async` (https://bugzilla.redhat.com/show_bug.cgi?id=1279127#c4) presumably because the word async happens to appear in the subject?

**Comment by ralphbean** [comment]
Yup.  We'll need something like a more conservative `short_desc_pattern` in the [method that tries to find matching review request bugs](https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/bz.py#L151-L165).  I tried to do matching example with a pattern like `"Review Request: %s" % name`, but it turned out that too many people used variations on that and not the same exact template.  Perhaps there is some middle-ground if we analyze the list of existing, open review requests.

**Comment by pypingou** [comment]
Another one here it seems: https://bugzilla.redhat.com/show_bug.cgi?id=1281532

**Comment by Zlopez** [comment]
After https://github.com/fedora-infra/the-new-hotness/pull/236 this shouldn't happen anymore, the bugzilla report is now matching the exact component and it's only considering issues reported by the-new-hotness itself.
