### ISSUE TITLE
Rawhide packages not found when source rpm not the same as binary rpm

### ISSUE THREAD

**Issue by tomhughes** [fedora-infra/the-new-hotness#84]
I have a couple of packages which are header only libraries where the source RPM is `foo` but the only binary rpms is `foo-devel` and the-new-hotness fails when it encounters them, for example:

```
the-new-hotness saw an update for catch, but no rawhide version of the package could be found yet
    https://release-monitoring.org/project/7680/
```

It appears that https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/repository.py#L40 is looking for a binary rpm called `catch` but there isn't one.

I'm not sure if uncommenting the `--archlist=src` would fix it? Certainly I know that with dnf you can do do it with:

```
dnf repoquery --all --srpm --qf="%{name}\t%{version}\t%{release}"
```

But in any case surely it's the src rpm that it should be looking for, as that is the name that will always match the pkgdb entry?

**Comment by ralphbean** [comment]
When I first wrote this, I used only the source list... but it got commented out for some reason in 2c1caf83f99161.  I wonder why...  You can see here in 3b9d136c0c8a (from around the same time) that I switched the yum config to use the binary kojira repos.

I agree.. we should switch this back to using src rpms if possible.

**Comment by ralphbean** [comment]
Ah, it looks like the rawhide repo from koji/kojira doesn't contain the source rpms (probably because it is only meant to be used internally).  It seems to me like:

- We can adjust the-new-hotness to no longer use the koji/kojira rawhide repo.  We can then use only the src rpms to solve problems like this.  We will be somewhat behind what has most recently been built in koji though.
- We can submit a patch to koji/kojira so that it also builds the source repo as well.  Then we can have the best of both worlds.

**Comment by tomhughes** [comment]
How about using `%{sourcerpm}` in the format string? So we query the binary rpms but get the names of their source rpms...

**Comment by tomhughes** [comment]
For example:

```
bericote [~] % sudo dnf repoquery --queryformat="%{name} %{sourcerpm}" catch*  
Last metadata expiration check performed 0:00:43 ago on Thu Nov 12 16:56:55 2015.
catch-devel catch-1.2.1-1.fc23.src.rpm
```

The old repoquery seems to have `base_package_name` as well which might be the simple name? That doesn't seem to be available in dnf though.

**Comment by tomhughes** [comment]
So this is the old yum repoquery:

```
bericote [~] % sudo repoquery --queryformat="%{name} %{base_package_name}" catch*
[sudo] password for tom: 

Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.


catch-devel catch
catch-devel catch
```

So `base_package_name` will work with the current code I think.

**Comment by ralphbean** [comment]
Coooooool.  :+1: to the approach.

**Comment by sergiomb2** [comment]
Hello I hit this  "the-new-hotness saw an update for python-gammu, but no rawhide version of the package could be found yet "
https://release-monitoring.org/project/8109/
https://apps.fedoraproject.org/packages/python-gammu

I think I found a dnf and yum bug because:

    dnf install python-gammu

doesn't respect  that python2-gammu provides python-gammu

    rpm -q python2-gammu --provides

python-gammu = 2.4-2.fc23
python2-gammu = 2.4-2.fc23
python2-gammu(x86-64) = 2.4-2.fc23

when in other cases it does  ( I just got one  example from RPMFusion dnf install VirtualBox-kmod-common ) 

    dnf repoquery  --queryformat="%{name} %{sourcerpm}" python-gammu 

python-gammu gammu-1.35.0-2.fc23.src.rpm

    dnf repoquery  --repoid=rawhide --enablerepo=rawhide --queryformat="%{name} %{sourcerpm}" python-gammu

no results 

    dnf repoquery  --repoid=rawhide --enablerepo=rawhide --queryformat="%{name} %{sourcerpm}" --whatprovides python-gammu

python2-gammu python-gammu-2.4-2.fc24.src.rpm

Conclusion maybe you should add "--whatprovides" in the query

**Comment by sergiomb2** [comment]
here is the better way to do the query:  
```
dnf repoquery --arch=src --disablerepo='*' --enablerepo=rawhide-source --qf="%{name} %{version} %{release} %{repoid}"  python-gammu

python-gammu 2.5 2.fc24 rawhide-source
```

**Comment by pypingou** [comment]
I wonder if a simple(r) solution wouldn't be to just query mdapi since I think it contains all the info we want

**Comment by rapgro** [comment]
qt-virt-manager is another sample where the-new-hotness fails to open new bugs. The spec creates two subpackes named virt-manager-qt4 or virt-manager-qt5.

**Comment by ralphbean** [comment]
> I wonder if a simple(r) solution wouldn't be to just query mdapi since I think it contains all the info we want

This is a great idea.

**Comment by ignatenkobrain** [comment]
https://github.com/fedora-infra/the-new-hotness/commit/2eed58c4ea09729f17e8c672196318d7028b0dba

**Comment by jeremycline** [comment]
@ignatenkobrain based on how I'm reading this issue and #98, both should be fixed by #128, correct?

**Comment by ignatenkobrain** [comment]
@jeremycline, yes

**Comment by jeremycline** [comment]
@ignatenkobrain thanks!

Closing as fixed in #128

**Comment by tomhughes** [comment]
Any idea when that fix is going to be deployed?

**Comment by jeremycline** [comment]
@tomhughes No, but I hope to at least tag a releases by the end of this week. Maybe early next week, fingers crossed?

**Comment by mrunge** [comment]
Any update on this? Is it now deployed? I just got 
`the-new-hotness saw an update for python-pelican, but no rawhide version of the package could be found yet
	https://release-monitoring.org/project/12763/`

**Comment by jeremycline** [comment]
It's not yet deployed. I need to get https://github.com/fedora-infra/the-new-hotness/pull/147 merged and I'd _really_ like to get https://github.com/fedora-infra/the-new-hotness/issues/145 in as well since it will make deploying the new version easier.
