### ISSUE TITLE
Stray update notification about an old upstream update

### ISSUE THREAD

**Issue by mschwendt** [fedora-infra/the-new-hotness#95]
This is related to the discussion thread at: https://lists.fedoraproject.org/archives/list/devel%40lists.fedoraproject.org/thread/IYQKQULU3Z2AJWA2DMBY5HSQEI4P5OLL/

On 2016-01-15, I received an email telling me:

> the-new-hotness saw an update for eiciel, but pkgdb says the maintainers are not
> interested in bugs being filed https://release-monitoring.org/project/8847/

No upstream update for eiciel has been released lately. Latest one is 0.9.11 from Sep 2015. Notifying about that release in Jan 2016 is dubious, since builds have been released for Fedora Rawhide and 23 in Dec 2015 already. However, at the day of the notification, somebody seems to have added the eiciel project to the release monitoring service, which may have triggered this bogus notification about an upstream release that is no update.

**Comment by ralphbean** [comment]
Part of the issue here is in consumers.py where we check for the pkgdb flag before we check against rawhide.  If the pkgdb flag says "no" we say "no" and stop.  But, the rawhide version *matches* -- if we would have checked that, we would've stopped without saying "no".  We should switch that order, I think.
